// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'curry_test.dart' as curry_test;
import 'either_test.dart' as either_test;
import 'extensions/int_test.dart' as extensions_int_test;
import 'extensions/iterable_test.dart' as extensions_iterable_test;
import 'maybe_test.dart' as maybe_test;
import 'random_test.dart' as random_test;
import 'result_test.dart' as result_test;

void main() {
  curry_test.main();
  either_test.main();
  extensions_int_test.main();
  extensions_iterable_test.main();
  maybe_test.main();
  random_test.main();
  result_test.main();
}
